apiVersion: v1
kind: ConfigMap
metadata:
  name: rideconnect-backend-config
  namespace: rideconnect
  labels:
    app.kubernetes.io/name: rideconnect-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: rideconnect-platform
data:
  # Application configuration
  LOG_LEVEL: "info"
  API_TIMEOUT: "30000"
  MAX_CONNECTIONS: "100"
  
  # Database configuration
  DB_POOL_MIN: "5"
  DB_POOL_MAX: "20"
  DB_TIMEOUT: "30000"
  
  # Session configuration
  SESSION_NAME: "rideconnect-session"
  SESSION_MAX_AGE: "86400000"  # 24 hours
  
  # Rate limiting
  RATE_LIMIT_WINDOW_MS: "900000"  # 15 minutes
  RATE_LIMIT_MAX_REQUESTS: "100"
  
  # CORS configuration
  CORS_ORIGIN: "true"
  CORS_CREDENTIALS: "true"
  
  # Health check configuration
  HEALTH_CHECK_TIMEOUT: "5000"
  READY_CHECK_TIMEOUT: "10000"