apiVersion: v1
kind: Service
metadata:
  name: rideconnect-backend
  namespace: rideconnect
  labels:
    app.kubernetes.io/name: rideconnect-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: rideconnect-platform
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: rideconnect-backend
    app.kubernetes.io/component: backend