# Production override for docker-compose
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

version: '3.8'

services:
  rideconnect:
    # Remove development volume mounts
    volumes: []
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - VITE_STRIPE_PUBLIC_KEY=${VITE_STRIPE_PUBLIC_KEY}
    
  # Keep MongoDB for production (you can remove this if using cloud MongoDB)
  mongodb:
    # In production, you might want to:
    # 1. Use a different volume path
    # 2. Use cloud MongoDB instead
    # 3. Add resource limits
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M