apiVersion: v1
kind: ServiceAccount
metadata:
  name: rideconnect-frontend
  namespace: rideconnect
  labels:
    app.kubernetes.io/name: rideconnect-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: rideconnect-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rideconnect-backend
  namespace: rideconnect
  labels:
    app.kubernetes.io/name: rideconnect-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: rideconnect-platform
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rideconnect-monitoring
  namespace: rideconnect
  labels:
    app.kubernetes.io/name: rideconnect-monitoring
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: rideconnect-platform
automountServiceAccountToken: true