apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rideconnect-frontend-hpa
  namespace: rideconnect
  labels:
    app.kubernetes.io/name: rideconnect-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: rideconnect-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rideconnect-frontend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max