apiVersion: v1
kind: Service
metadata:
  name: rideconnect-frontend
  namespace: rideconnect
  labels:
    app.kubernetes.io/name: rideconnect-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: rideconnect-platform
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/nginx_status"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: rideconnect-frontend
    app.kubernetes.io/component: frontend