# ServiceMonitor configurations for existing Prometheus setup
# These will integrate RideConnect with your existing monitoring infrastructure

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rideconnect-backend-metrics
  namespace: rideconnect
  labels:
    app.kubernetes.io/name: rideconnect-backend
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: rideconnect-platform
    # Add label that your existing Prometheus uses to discover services
    prometheus: kube-prometheus  # Adjust based on your Prometheus setup
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rideconnect-backend
      app.kubernetes.io/component: backend
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: service
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'go_.*'
      action: drop  # Drop Go runtime metrics if not needed
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rideconnect-frontend-metrics
  namespace: rideconnect
  labels:
    app.kubernetes.io/name: rideconnect-frontend
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: rideconnect-platform
    # Add label that your existing Prometheus uses to discover services
    prometheus: kube-prometheus  # Adjust based on your Prometheus setup
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rideconnect-frontend
      app.kubernetes.io/component: frontend
  endpoints:
  - port: http
    path: /nginx_status
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: service
---
# PodMonitor for additional pod-level metrics
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rideconnect-pods
  namespace: rideconnect
  labels:
    app.kubernetes.io/name: rideconnect-pods
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: rideconnect-platform
    prometheus: kube-prometheus  # Adjust based on your Prometheus setup
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: rideconnect-platform
  podMetricsEndpoints:
  - port: http
    path: /metrics
    interval: 30s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
      targetLabel: component