apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: rideconnect-development

namespace: rideconnect-dev

resources:
- ../../base/namespace
- ../../base/rbac
- ../../base/frontend
- ../../base/backend
- ../../base/database/statefulset.yaml  # Use in-cluster MongoDB for development
- ../../base/ingress
- ../../base/network-policies
- ../../base/monitoring

patches:
- target:
    kind: Deployment
    name: rideconnect-frontend
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 50m
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 64Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 200m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 128Mi

- target:
    kind: Deployment
    name: rideconnect-backend
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 200m
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 256Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 500m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 512Mi

- target:
    kind: HorizontalPodAutoscaler
    name: rideconnect-frontend-hpa
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 1
    - op: replace
      path: /spec/maxReplicas
      value: 3

- target:
    kind: HorizontalPodAutoscaler
    name: rideconnect-backend-hpa
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 1
    - op: replace
      path: /spec/maxReplicas
      value: 2

- target:
    kind: Ingress
    name: rideconnect-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: rideconnect-dev.yourdomain.com
    - op: replace
      path: /spec/tls/0/hosts/0
      value: rideconnect-dev.yourdomain.com

images:
- name: rideconnect-frontend
  newTag: latest
- name: rideconnect-backend
  newTag: latest

configMapGenerator:
- name: rideconnect-backend-config
  behavior: merge
  literals:
  - NODE_ENV=development
  - LOG_LEVEL=debug
  - RATE_LIMIT_MAX_REQUESTS=1000

secretGenerator:
- name: rideconnect-secrets
  literals:
  - mongodb-uri=mongodb://rideconnect-mongodb:27017/rideconnect
  - admin-key=admin123
  - session-secret=dev-session-secret

commonLabels:
  environment: development
  version: latest