apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: rideconnect-production

namespace: rideconnect

resources:
- ../../base/namespace
- ../../base/rbac
- ../../base/frontend
- ../../base/backend
- ../../base/database/external-config.yaml  # Use external MongoDB for production
- ../../base/ingress
- ../../base/network-policies
- ../../base/monitoring

patches:
- target:
    kind: Deployment
    name: rideconnect-frontend
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: rideconnect-frontend:latest

- target:
    kind: Deployment
    name: rideconnect-backend
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: rideconnect-backend:latest

- target:
    kind: HorizontalPodAutoscaler
    name: rideconnect-frontend-hpa
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 3
    - op: replace
      path: /spec/maxReplicas
      value: 10

- target:
    kind: HorizontalPodAutoscaler
    name: rideconnect-backend-hpa
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 3
    - op: replace
      path: /spec/maxReplicas
      value: 8

- target:
    kind: Ingress
    name: rideconnect-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: rideconnect.yourdomain.com
    - op: replace
      path: /spec/rules/1/host
      value: api.rideconnect.yourdomain.com
    - op: replace
      path: /spec/tls/0/hosts/0
      value: rideconnect.yourdomain.com
    - op: replace
      path: /spec/tls/0/hosts/1
      value: api.rideconnect.yourdomain.com

- target:
    kind: NetworkPolicy
    name: allow-backend-database-egress
  patch: |-
    - op: replace
      path: /spec/egress/0/to
      value: []  # Allow external MongoDB Atlas connection

images:
- name: rideconnect-frontend
  newTag: latest
- name: rideconnect-backend
  newTag: latest

configMapGenerator:
- name: rideconnect-backend-config
  behavior: merge
  literals:
  - NODE_ENV=production
  - LOG_LEVEL=info
  - RATE_LIMIT_MAX_REQUESTS=100
  - API_TIMEOUT=10000

# Production secrets should be created separately and not in git
# Use external secret management like:
# - Kubernetes Secrets created via kubectl
# - External Secrets Operator
# - HashiCorp Vault
# - Cloud provider secret managers

commonLabels:
  environment: production
  version: latest

replicas:
- name: rideconnect-frontend
  count: 3
- name: rideconnect-backend
  count: 3