# TLS Certificate configuration using cert-manager
# Requires cert-manager to be installed in the cluster

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app.kubernetes.io/name: letsencrypt-prod
    app.kubernetes.io/component: cert-manager
    app.kubernetes.io/part-of: rideconnect-platform
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    
    # Email address used for ACME registration
    email: admin@yourdomain.com  # Replace with your email
    
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app.kubernetes.io/name: letsencrypt-staging
    app.kubernetes.io/component: cert-manager
    app.kubernetes.io/part-of: rideconnect-platform
spec:
  acme:
    # The ACME server URL (staging)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    
    # Email address used for ACME registration
    email: admin@yourdomain.com  # Replace with your email
    
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
---
# Manual certificate for development/testing
apiVersion: v1
kind: Secret
metadata:
  name: rideconnect-tls-manual
  namespace: rideconnect
  labels:
    app.kubernetes.io/name: rideconnect-tls
    app.kubernetes.io/component: tls
    app.kubernetes.io/part-of: rideconnect-platform
type: kubernetes.io/tls
data:
  # Base64 encoded certificate and key
  # Replace with your actual TLS certificate and private key
  tls.crt: LS0tLS1CRUdJTi... # Your certificate in base64
  tls.key: LS0tLS1CRUdJTi... # Your private key in base64