apiVersion: v1
kind: Namespace
metadata:
  name: rideconnect
  labels:
    app.kubernetes.io/name: rideconnect
    app.kubernetes.io/instance: production
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: rideconnect-platform
    monitoring: "enabled"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rideconnect-quota
  namespace: rideconnect
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    persistentvolumeclaims: "4"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: rideconnect-limits
  namespace: rideconnect
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
  - default:
      storage: 1Gi
    type: PersistentVolumeClaim